space-syndicate/space-station-14-next

Content.Shared/Research/Prototypes/TechDisciplinePrototype.cs, Resources/Prototypes/Research/disciplines.yml
Изменил цифру блокировки изучения технологий на Т4
Даст больше мотиваций для исследований технологий в RnD, больше возможностей для игры.
Баланс: Считаю, что влияние будет минимальным, так как при текущих реалиях онлайна и экипажа не всегда исследуется даже четверть или пятая часть всех технологий.
Ссылка на предложение в дискорд сервере: https://discord.com/channels/919301044784226385/1301821257695887411
Изменение одной циферки по пути Content.Shared/Research/Prototypes/TechDisciplinePrototype.cs
:cl:
- tweak: Теперь можно исследовать Т3 технологии всех дисциплин
=> Move discipline lock from T3 to T4

Resources/Prototypes/Corvax/Maps/astra.yml, Resources/Prototypes/Corvax/Maps/avrite.yml, Resources/Prototypes/Corvax/Maps/delta.yml, Resources/Prototypes/Corvax/Maps/maus.yml, Resources/Prototypes/Corvax/Maps/paper.yml, Resources/Prototypes/Corvax/Maps/pearl.yml, Resources/Prototypes/Corvax/Maps/pilgrim.yml
Добавляет роль бригмедика ( #31 ), использует уже замапленные кочергой спавнеры (https://github.com/space-syndicate/space-station-14/pull/2759)
Бригмедик теперь полностью в игре!
:cl:
- add: Добавлена роль бригмедика на Астру
- add: Добавлена роль бригмедика на Аврит
- add: Добавлена роль бригмедика на Дельту
- add: Добавлена роль бригмедика на Маус
- add: Добавлена роль бригмедика на Пейпер
- add: Добавлена роль бригмедика на Пёрл
- add: Добавлена роль бригмедика на Пилгрим
=> brigmedic spawn roles

Content.Client/Corvax/TTS/TTSSystem.cs
Возможно, я починил TTS при переподключении.
`_contentRoot` диспозали, а новый не создавали. Исправлено.
На самом деле, должен создаваться новый экземпляр класса при переподключении, но, как мы видим, не создаётся.
:cl:
- fix: Возможно, TTS теперь будет работать при переподключении.
=> Possible TTS fix

Content.Server/Zombies/ZombieSystem.Transform.cs, Content.Shared/Zombies/PendingZombieComponent.cs, Content.Shared/Zombies/ZombieComponent.cs
Бафф зомби. Если точнее то большая часть характеристик у зомби были бафнуты - дабы сделать их серьезной угрозой для станции. Сразу говорю! Это мой первый PR в жизни! возможны ошибки!
Сейчас зомби крайне слабые, они редко побеждают в раундах, а процент заражения станции к концу раунда редко достигает хотя-бы 40%. Самих зомби игроки уже просто прозвали грушами для битья - их легко убить особенно на расстоянии. Сами же игроки на зомби часто жаловались на ужасную скорость зомби. 
Раунды где богами рандома выпадала зомба становились очень скучными, зомбей подавляли за 10-20 минут после вспышки, заражались лишь сами нулевые и невнимательные игроки. А те ко и заразился от вируса - мог дожить до конца раунда просто чилово подождав Амбузол. Пока ждут амбузол они просто едят/пьют диловен или СПЯТ В …
=> Zombie buff

Content.Shared/Body/Systems/SharedBodySystem.Body.cs
Части тела сейчас нельзя уничтожить, которые вывалились с тела. Это фиксит баг с вываливанием мозгов с головы и уничтожением частей тела.
Мозг достать из головы не выйдет простыми способами (slash, blunt, heat уроном), нужна дробилка, мусоропереработчик, миксер и т.д.
Опечатку исправил, должно было в двух местах удаляться, но почему-то удаляется только со стороны тела.
:cl:
- fix: Теперь части тела могут быть уничтожены! Например уничтожить голову для получения мозга.
=> [Hotfix] Хирургия части тела теперь уничтожаемы

Content.Shared/Body/Part/BodyPartComponent.cs, Content.Shared/Body/Systems/SharedBodySystem.Body.cs, Resources/Prototypes/Body/Parts/base.yml
Органы частей тела теперь полностью выпадают, даже если уничтожить часть тела прикреплённые к туловищу огромным количеством урона (например микробомба), то органы внутри части тела выпадут (если эти органы имеются, например в голове мозги и глаза выпадут).
Уменьшил структурный порог частей тела на 25%, чтобы части тела выпадали после получения 70 урона (было раньше 90), вместо прямого уничтожения части тела (где хотелось-бы получить этот кусок тела, а не уничтожить его).
Фикс исправляет по нормальному, вместо временного хотфикса, который решал последствия а не багу.
Добавил отдельный учёт выпадения органов с части тела на теле при уничтожении. Часть тела или само тело и так без багов удаляется.
:cl:
- fix: Теперь части тела имеют меньший максимальный порог …
=> [Fix] Хирургия фикс выпадения органов у частей тела вместо хотфикса

Resources/Prototypes/Body/Organs/reptilian.yml
Убрана принудительная диета у унатхов.
Что мы получаем имея этот высер?
- Унатх превращается в раба системы, который не может сожрать шоколадный пончик, потому-что... вселенная не позволяет засунуть его в рот? Потому-что НТ вставило чип, запрещающий унатхам совать определённую еду в рот?...
Почему это нужно вернуть?
- Унатх и так отравится, если сожрёт то что нельзя, но так он хотя-бы **сможет** это сделать, это игра про свободу и её последствия.
:cl: PuroSlavKing
- remove: Удалена диета унатхов, они снова могут съесть что-то не то и откинутся.
=> [Tweak] Remove Lizard Diete

Content.Client/Corvax/TTS/TTSSystem.cs
Вторая попытка починить TTS, который ломается после переподключения.
Видимо, новый экземпляр правильно создавался. Но, видимо, не создаётся новый экземпляр `ResourceManager`. То есть добавлялся ContentRoot по указанному пути, его нормально использовали, а когда появлялся новый `ContentRoot`, то он путь не перезаписывал, а баговался. Сейчас мы создаём один `ContentRoot`, не дизпозаем его и добавляем только один раз.
:cl:
- fix: Возможно, починен TTS, который ломался после переподключения.
=> Possible TTS fix 2

Content.Server/Zombies/ZombieSystem.Transform.cs, Content.Shared/Zombies/PendingZombieComponent.cs, Content.Shared/Zombies/ZombieComponent.cs
увы, бафать скорость зомби была не лучшей идеей.
Я не ожидал что повышение скорости на 10% так сильно их ускорит, зомби были через чур быстрыми. + Администратор и некоторые люди жаловались на высокий стамин урон. Все изменения я сделал исходя из наблюдений 3 раундов с бафнутыми зомби(2 с мейна и 1 с атары).
:cl:
- tweak: Урон по стамине снижен с 25 до 15
- tweak: Урон от вируса и регенерация зомби была чуть чуть уменьшена(на 0.1)
- tweak: Время через которое вирус начнет убивать повышенно на 5 минут. У игрока в сумме будет максимум 30 минут, а после гарантированная смерть.
- tweak: дебафф к скорости зомби понижена к 75%, У старых зомби было 70, а у жутко бафнутых 80.
-->
=> zombie balance fix (no more грууаааа......)

Content.Shared/_CorvaxNext/Standing/SharedLayingDownSystem.cs
Thats basically happens on client side, because of bugs on DoAfter side.
ССДшники теперь не пытаются встать на ноги когда упали в критическое состояние или погибли.
Это выглядит ужасно, когда над трупом несколько doAfter'ов, которые никогда не исчезнут, даже если человека "ударить дефибриллятором".
Добавил проверку, что персонаж ССД, если он ССД, то тогда DoAfter скрывается. По сути показывается только для этого ССДшника локально, но так как его не существует, то ничего не происходит и она уходит. Сам баг на стороне клиента.
:cl:
- fix: Игроки в ССД после смерти больше не пытаются встать на ноги!
=> [Fix] Laying System SSD tries to stand up infinitely

Content.Shared/Inventory/InventorySystem.Slots.cs
Basically reverts disabling feature of limbs cutting
Исправил откатив фичу с исчезанием слотов при отрубании конечностей. Эта фича багованная нужно переписать. Сегодня будет пофикшено, но чтобы игроки не страдали, откатил эту фичу со слотами. Слоты будут левитировать, но зато игроки не будут страдать.
https://discord.com/channels/919301044784226385/1309856788346044416/1311175685599006730
Система слотов ломается из-за щиткода на стороне оффов. Я просто закомментировал фичу `//slot.Disable = isDisabled;` в `InventorySystem.Slots.cs`. Вот подробности про багу:
> I think I moved everything related to slot disabling/enabling to a centralized function called ChangeSlotState or something?
> its really messy since `inventorycomponent` and `inventoryslotscomponent` are not the same.
> and …
=> [Hotfix] Inventory slots dissapear at roundstart

Resources/Locale/ru-RU/_corvaxnext/interaction/offer-item-system.ftl
Убрал функции THE() из локализации
THE() используется для английской локализации
:cl: csqrb
- fix: Поправлен текст при передаче предметов
=> Супер мелкий фикс локализации при передаче предметов

Content.Server/Fluids/EntitySystems/PuddleSystem.cs, Content.Shared/Fluids/Components/PuddleComponent.cs, Resources/Prototypes/_CorvaxNext/Entities/Effects/footstep.yml
Вязкость реагентов в следах теперь не влияют на скорость движения игроков, что ходят на по ним.
Незачем делать лужи вязких веществ ещё неприятнее
Поле `ViscosityAffectsMovement` в `PuddleComponent`, отключающее обновление замедления у объекта, если оно `false`
https://github.com/user-attachments/assets/e95eaa69-ab4d-4db4-870b-6c61864fe838
нету
:cl: csqrb
- tweak: Следы от вязких реагентов больше не замедляют персонажа.
=> Вязкость реагентов следов теперь не влияет на скорость движения

Content.Server/Doors/Systems/DoorSystem.cs, Content.Server/Forensics/Systems/ForensicsSystem.cs, Content.Shared/Doors/Systems/SharedDoorSystem.cs
Раньше шлюзы сохраняли отпечатки пальцев только если по ним прямо ткнуть мышкой. Если просто проходить сквозь них, то ничего не сохранялось.
Теперь при открытии шлюза тушкой (что подразумевает, что вы типа открываете шлюз рукой) отпечатки пальцев так же сохраняются на двери и могут быть просканированы анализатором детектива. Прохождение через уже открытый шлюз не сохраняет отпечатки.
Потому что текущее состояние этой системы, требующее именно нажатия на дверь мышкой для сохранения отпечатков - бред.
:cl:
- tweak: Все шлюзы теперь всегда сохраняют отпечатки пальцев (или тип перчаток) при их открытии проходом через них, а не только когда по ним жмешь курсором для открытия.
=> Открытие шлюзов всегда сохраняет отпечатки.

Content.Server/_CorvaxNext/Storage/AnchorableStorageComponent.cs, Content.Server/_CorvaxNext/Storage/AnchorableStorageSystem.cs, Resources/Locale/en-US/_corvaxnext/storage/anchorable-storage.ftl, Resources/Locale/ru-RU/_corvaxnext/storage/anchorable-storage.ftl, Resources/Prototypes/Catalog/VendingMachines/Inventories/detdrobe.yml, Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
Сумки, рюкзаки и прочие мешки теперь можно прятать под плитками пола. Для этого необходимо снять напольную плитку и гаечным ключом прикрутить сумку, после чего положить поверх плитку. В меди на скриншоте всё будет понятно описано.
Спрятаные под полом сумки видно на т-лучевом сканере. Так же, два таких сканера добавлены в шкафчик детектива.
Портировано с https://github.com/new-frontiers-14/frontier-station-14/pull/2347, но было выпилено из кода все что связано с системами Няно (перенос людей в сумке и т.д.).
Преступления это весело.
https://discord.com/channels/919301044784226385/1307344811933831241
N/A - система самодостаточна и не изменяет сторонние файлы кода.
:cl:
- add: Сумки теперь можно прятать под плитками пола!
=> Сумки можно прятать под плитки пола.

Content.Server/GameTicking/GameTicker.Spawning.cs, Content.Server/GameTicking/Rules/ZombieRuleSystem.cs
Изменена механика автоматического вызова шаттла для зомби-режима:  
- Теперь проверка корректно учитывает только **основную станцию**, исключая ЦК, планетарные экспедиции, обломки, шаттлы и всё остальное.  
- Игроки, инфицированные зомби-вирусом, больше не считаются "здоровыми" для расчета вызова шаттла, что предотвращает затягивание раунда.  
- Мертвые игроки-зомби теперь учитываются при вызова шаттла, так как они считаются исключенными из раунда.  
- Игроки, покинувшие станцию, больше не считаются "здоровыми членами экипажа" для вызова шаттла.
Эти изменения предотвращают затягивание раундов зомби-режима. Теперь вызов эвакуационного шаттла будет происходить корректно в случаях, когда большинство игроков исключено из игры (умерло или покинуло станцию). Это улучшит общий игровой процесс и …
=> Улучшение механики автовызова эвакуации для зомби-раундов

Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
В шкафчике СМО теперь спавнится плата мед. биофаба
Важно отметить, что плата мед. биофаба не требует никаких частей при сборке. Их добавляет вот этот [PR](https://github.com/space-syndicate/space-station-14-next/pull/142)
В внутригровом гайде говорится, что плата мед. биофаба есть в шкафчике СМО, но её там нету.
Если она не должна быть раундстартовой в шкафчике СМО, то нужно поправить гайд
прототипы
:cl: csqrb
- fix: В шкафчие главного врача теперь есть плата медицинского фабрикатора.
=> Плата мед. биофаба в шкафчике СМО

Content.Server/_CorvaxNext/Weapons/Ranged/Systems/FireOnDropSystem.cs, Content.Shared/Weapons/Ranged/Components/GunComponent.cs, Resources/Prototypes/Entities/Objects/Weapons/Guns/Basic/base_pka.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/pistols.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Revolvers/revolvers.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
Теперь если бросить оружие оно имеет небольшой шанс выстрелить при столкновении с другим объектом.
Портировано с https://github.com/Simple-Station/Einstein-Engines/pull/471
Fun.
https://github.com/user-attachments/assets/1a093378-c9c8-480c-a445-dc2b258cb392
Было внедрено дополнительное поле в GunComponent
:cl:
- add: Оружие имеет небольшой шанс выстрелить в случайном направлении при падении.
=> [Port] Случайные выстрелы при падении оружия

Content.Server/_CorvaxNext/DynamicHostname/DynamicHostnameSystem.cs, Resources/Locale/ru-RU/_CorvaxNext/dynamichostname/hostname.ftl
Добавил динамическое название сервера в зависимости от его состояния
SS13 Content
Ничего такого, простецкая система
Ничего такого
:cl:
- add: Теперь в названии сервера указывается его состояние в раунде!
=> Dynamic Hostname System

Content.Shared/Verbs/VerbCategory.cs, Content.Shared/_CorvaxNext/TurretControl/TurretControlComponent.cs, Content.Shared/_CorvaxNext/TurretControl/TurretControlSystem.cs, Resources/Locale/ru-RU/_corvaxnext/turret-control.ftl, Resources/Locale/ru-RU/_corvaxnext/verbs.ftl, Resources/Locale/ru-RU/ss14-ru/prototypes/_corvaxnext/entities/objects/weapons/guns/turrets.ftl, Resources/Prototypes/Entities/Objects/Weapons/Guns/turrets.yml, Resources/Prototypes/_CorvaxNext/Entities/Objects/Weapons/Guns/turrets.yml, Resources/Prototypes/_CorvaxNext/ai_factions.yml
Теперь ЦИИ может с помощью ПКМ настроить турели на атаку по определённым целям.
Есть 3 режима целей:
- Никто
- Враждебные
- Все
Но он может настраивать только турели с определённым компонентом, которых пока что нет на картах.
Возможность противостоять АПИИ и дракону.
https://discord.com/channels/919301044784226385/1319063870073081891
:cl:
- add: Теперь ЦИИ может настраивать, по кому бьют турели. Требует маппинга.
=> Настраиваемые турели

Content.Shared/_CorvaxNext/NextVars.cs, Resources/Prototypes/Entities/Mobs/Species/base.yml
Продолжение вот этого PRа - https://github.com/space-syndicate/space-station-14-next/pull/209
Теперь все игроки, чьи тела живы и находятся на станции, будут автоматически телепортироваться в криокамеру спустя 20 минут после выхода с сервера для освобождения занимаемой должности.
Всё авторство кода принадлежит автору оригинального PRа, я просто включаю его действие и увеличиваю таймер до 20 минут по итогам тестирования.
Небольшой QOL для освобождения занятых ролей, в случае если какой-нибудь клоун резко вышел из игры будучи в техах и никем не был найден.
Всем тушкам добавлен компонент AutoCryoSleepable, который запускает двадцатиминутный таймер по выходу игрока с сервера.
:cl:
- add: Теперь все живые игроки, вышедшие с сервера и находящиеся на станции, автоматически …
=> Система автоматического телепортирования в криокапсулы

Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs, Content.Server/_CorvaxNext/FTLKnockdownImmune/FTLKnockdownImmuneComponent.cs, Resources/Prototypes/Entities/Mobs/Species/diona.yml
Дионы теперь не падают из-за блюспейс прыжков.
Потому что лор, они деревья, они крепко стоят на ногах.
:cl:
- tweak: Дионы больше не падают при БСС прыжках на шаттлах.
=> Дионы теперь не падают при БСС

Content.Server/_CorvaxNext/CartridgeLoader/Cartridges/NanoChatCartridgeSystem.cs, Content.Shared/_CorvaxNext/NanoChat/NanoChatCardComponent.cs, Content.Shared/_CorvaxNext/NanoChat/SharedNanoChatSystem.cs
Теперь оповещения о сообщениях из НаноЧата появляются даже если КПК и приложение на нём закрыты. Раньше с этим были проблемы.
Теперь НаноЧат работает не на одной станции, а по всей карте (но только в рамках одной карты, с улетевшими утилями не поболтаете).
Порт багфикса наночата - https://github.com/DeltaV-Station/Delta-v/pull/2565
Порт глобализации наночата - https://github.com/impstation/imp-station-14/pull/1055
Багфикс.
:cl:
- fix: Теперь всегда оповещения о новых сообщениях НаноЧата.
- tweak: Теперь НаноЧат доставляет сообщения в радиусе карты, а не станции.
=> Багфикс Наночата

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml, Resources/Prototypes/Roles/Jobs/Medical/chemist.yml, Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml, Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml, Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml, Resources/Prototypes/_CorvaxNext/Roles/Jobs/Medical/surgeon.yml, Resources/Prototypes/_CorvaxNext/Roles/Jobs/Security/brigmedic.yml, Resources/Prototypes/borg_types.yml
Мелкие фиксы хирургии. Борги вновь могут делать операции, врачи теперь имеют работающий бафф к скорости хирургии, хирург тоже, борги теперь могут выбирать куда целиться как игроки.
https://github.com/Goob-Station/Goob-Station/pull/1280 - раньше компонент, ускорявший хирургию для врачей и прочих, банально не работал.
https://github.com/Goob-Station/Goob-Station/pull/1294 - Борги теперь могут выбирать куда бить или лечить.
https://github.com/Goob-Station/Goob-Station/pull/1231 - медборги теперь умеют в хирургию.
:cl:
- fix: Исправлена работа баффа скорости хирургии.
- fix: Медицинские борги теперь умеют делать операции.
- tweak: Борги теперь могут выбирать куда целиться на тушке человека.
=> Навыходившие фиксы хирургии

Content.Client/_CorvaxNext/Emoting/AnimatedEmotesSystem.cs, Content.Server/Chat/Systems/ChatSystem.Emote.cs, Content.Server/_CorvaxNext/Emoting/AnimatedEmotesSystem.cs, Content.Shared/Chat/Prototypes/EmotePrototype.cs, Content.Shared/_CorvaxNext/Emoting/AnimatedEmotesComponent.cs, Content.Shared/_CorvaxNext/Emoting/SharedAnimatedEmotesSystem.cs, Resources/Locale/ru-RU/_corvaxnext/emotes.ftl, Resources/Prototypes/Entities/Mobs/base.yml, Resources/Prototypes/_CorvaxNext/Actions/emotes.yml
Добавлены три анимированные анимации - прыжи, кувырки и развороты. Доступны через меню быстрых эмоций или по триггерам в чате эмоций: "кувырок", "сальто", "кружится", "вращается", "прыгает" и так далее.
Портировано по большим просьбам в из:
https://github.com/Goob-Station/Goob-Station/pull/828
https://github.com/Goob-Station/Goob-Station/pull/832
https://github.com/user-attachments/assets/fba01065-e089-4505-82df-35411c7feb01
:cl:
- add: Добавлено три анимированных эмоции - прыжок, кувырок и разворот.
=> [PORT] animated emoting

Resources/Prototypes/Catalog/Cargo/cargo_food.yml, Resources/Prototypes/Catalog/Fills/Boxes/emergency.yml
- Шоколадная штука в Аварийном наборе заменена на энергетический батончик.
- Изменена стоимость грузов: 
- - 4 пиццы — 450 -> 900
- - 16 пиццы — 1800 -> 3600
- - ИРП — 1000 -> 2000
Изменения направлены на увеличение спроса на еду, чтобы люди чаще пользовались услугами повара, и его вклад в раунд был более значительным. Тем самым увеличиваем интерес игры на данной роли.
В скором времени количество торгоматов с едой на хайпоп и мидпоп картах будет тоже порезано,
:cl: Ko4erga
- tweak: Еда в аварийном наборе заменена на энергетический батончик.
- tweak: Стоимость заказа грузов с готовой едой была повышена в два раза.
=> Survival box & cargo prices

Resources/Prototypes/Entities/Objects/Power/portable_recharger.yml, Resources/Prototypes/Entities/Structures/Power/chargers.yml
Теперь нельзя использовать настенный зарядник/переносной зарядник для зарядки плазменного резака. Вместо этого используйте плазму.
https://github.com/user-attachments/assets/c31aecea-1cdf-4b9a-a4d1-3671f4a1a450
:cl:
- fix: Исправлено: настенный зарядник, переносной зарядник больше не подходят для зарядки плазменного резака.
=> fix-charge

Resources/Prototypes/Corvax/Maps/Next/omega.yml
Убран случайный поворот станции раундстартом
Случайный поворот станции конфликтовал со спасательными капсулами (в связи с добавлением новой механики поломки гридов), из-за чего в самом центре карты полностью ломалось покрытие, создавая раундстартовую разгерметизацию.
[Ветка обсуждения Омеги и её ПРов](https://discord.com/channels/919301044784226385/1325808875588419725)
:cl: Aireki
- fix: Исправлена раундстартовая разгерметизация в центре карты, путём удаления случайного поворота у станции.
=> [Maps] Omega prototype hotfix

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/_CorvaxNext/Recipes/Lathes/Packs/botany.yml
Исправил ошибку из за которой анализатор растений можно было раундстартом печатать в автолате, а в протолате невозможно даже после соответствующего исследования.
Анализатор растений является исследуемым предметом в ветке сервиса, возможность печатать его раундстартом в автолате не круто.
Переименовал PlantanalyzerStatic в PlantAnalyzerDynamic.
Удалил PlantanalyzerStatic из рецептов автолата.
Добавил PlantAnalyzerDynamic в динамические рецепты протолата.
В PlantAnalyzerDynamic заменил рецепт Plantanalyzer на исследуемую в РНД версию PlantAnalyzer.
=> Fix Plant Analyzer

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
- Емкость магазина увеличена с 16-ти выстрелов до 30-ти.
- Скорострельность увеличена с 2 до 2.25.
- Емкость магазина увеличена с 10-ти выстрелов до 15-ти.
Ну, теперь это можно хотя бы назвать оружием. Повышена именно ёмкость батареи, благодаря чему скорость зарядки до прежних значений останется той же.
https://discord.com/channels/919301044784226385/1374036263270748312
:cl: Ko4erga
- tweak: Улучшены характеристики лазерного карабина и лазерной пушки.
=> Laser guns rebalance

Resources/Prototypes/_Lavaland/Reagents/medicine.yml
Исправлен баланс медипена и реагента
Основной дамаг (15u ядами и 15u холодом) теперь наносятся только на лаваленде. Был добавлен урон в случае нахождения вне лаваленда при 41u утилеславина в крови (>2 медипенов). Урон вне лавы составляет 0.5 ядами (10u за медипен).
Чтоб убить условного человека вне лаваленда потребуется вкинуть ему около 12 медипенов.
=> Minerssalve balance

Content.Server/Administration/Systems/AdminVerbSystem.cs, Content.Server/_CorvaxNext/Administration/Systems/AdminVerbSystem.Smites.cs, Resources/Locale/en-US/_corvaxnext/administration/smites.ftl, Resources/Locale/ru-RU/_corvaxnext/administration/smites.ftl, Resources/Prototypes/_CorvaxNext/Entities/Effects/lightning.yml
Добавлена новая божья кара - удар молнии. Наносит 35 урона электричеством, оглушает цель на 3 секунды.
Удобная штука чтобы карать серунчиков в чат или двухклятых ЕРПешеров. По сравнению с остальными карами, эта выглядит более менее РПшнее и не смертельнее, чем те, что в стиле "превратить в обезьяну", "обескровить", "кикнуть пингом".
https://github.com/user-attachments/assets/febad511-057a-4de3-98cf-339afb6e9380
=> Lightning bolt smite

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Киборги могут чинить самих себя. Увеличено время самопочинки до 60 секунд.
Не всегда у киборга есть возможность попасть до людей с сварочной маской и сваркой, по сути это только учёные и инженеры, особенно, если киборг занимается автономными задачами в космосе. Если типу не впадлу стоять неподвижно минуту то почему бы и нет
=> Cyborgs can repair themself now
