Resources/Prototypes/_CorvaxNext/Entities/Effects/footstep.yml
улучшил следы
потому что кринж
прототипы
не
:cl:
- tweak: Следы стали больше похожи на лужи, теперь их можно: осматривать (и с помощью хим визора), благословить, ПИТЬ, набирать шприцом. Из них не будут пить животные и перенос ДНК стал лучше.
=> footsteps 2 electric boogaloo

Resources/Prototypes/_CorvaxNext/Entities/Structures/Machines/bluespace_harvester.yml
- Увеличил прочность 350 -> 1250
- При уничтожении дополнительно взрывается
Легкий гриф цели.
:cl:
- fix: Исправлены характеристики БСХ
=> Bluspace Harvester rebalance

Content.Shared/_CorvaxNext/NextVars.cs
теперь нельзя лазать под столами 
нельзя попасть по человеку, который под столом
:cl: Ratyyy
- tweak: Отключено ползания под столами во избежании подстольных воин!
=> отключение подстольных воин

Resources/Prototypes/game_presets.yml
Позволяет админам создавать голосования на режим игры, где будет не только "секрет".
Потому что почему нет?
:cl:
- tweak: Теперь в голосовании за режим будут отображаться все _адекватные_ режимы.
=> Вкус демократии

Content.Shared/CombatMode/CombatModeComponent.cs, Content.Shared/CombatMode/SharedCombatModeSystem.cs
персонажи теперь вращаются на все полные, красивые 360°. Ну, кроме спрайтиков. Спрайтики всё ещё двухмерные, с четырьмя направлениями. Зато какие теперь классные фонарики!
https://github.com/user-attachments/assets/24de2109-51a6-4798-842e-d714b0b526fa
Порт с ВВДП. https://github.com/WWhiteDreamProject/wwdpublic/pull/141
Красиое
Почти ничего не поменялось
в описании
Почти ничего не поменялось
- add: В тестовом режиме: персонажи теперь вращаются на все полные, красивые 360°. Ну, кроме спрайтиков. Спрайтики всё ещё двухмерные, с четырьмя направлениями. Зато какие теперь классные фонарики!
=> NoScope 360 AWP kill

Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Research/civilianservices.yml, Resources/Prototypes/_CorvaxNext/Entities/Objects/Circuitboards/production.yml, Resources/Prototypes/_CorvaxNext/Recipes/Lathes/circuit_boards.yml
Рецепт мед. биофаба теперь существует и его можно открыть из технологии "Манипулирование мясом".
Прежде недоступная плата мед. биофаба теперь требует компоненты при создании машины из неё.
Мед. биофаб невозможно получить.
https://discord.com/channels/919301044784226385/1315604234368057414
прототипы
:cl: csqrb
- add: Теперь можно изучить и собрать медицинский биофабрикатор для получения синтетических конечностей.
=> Изучаемый мед. фабрикатор

Resources/Prototypes/Corvax/Maps/astra.yml, Resources/Prototypes/Corvax/Maps/avrite.yml, Resources/Prototypes/Corvax/Maps/awesome.yml, Resources/Prototypes/Corvax/Maps/delta.yml, Resources/Prototypes/Corvax/Maps/maus.yml, Resources/Prototypes/Corvax/Maps/paper.yml, Resources/Prototypes/Corvax/Maps/pilgrim.yml, Resources/Prototypes/Corvax/Maps/tushkan.yml
Добавил роли хирурга на Астру, Аврит, Авесом, Дельту, Маус, Пейпер, Пилигрим, Тушкан
Вернул бригмеда на пейпер и аврит.
:cl:
- add: Добавил роли хирурга на Астру, Аврит, Авесом, Дельту, Маус, Пейпер, Пилигрим, Тушкан
- tweak: Вернул бригмеда на пейпер и аврит.
=> spawnroles

Resources/Prototypes/_CorvaxNext/Roles/Jobs/Medical/surgeon.yml
Вместо 10 часов за доктора поставил 15 часов в меде.
Я на химике играю мне не хватает :sob:
:cl:
- tweak: Теперь для роли хирурга вместо 10 часов за доктора надо 15 часов в отделе.
=> Update Surgeon role playtime

Resources/Prototypes/Corvax/Entities/Markers/Spawners/jobs.yml
=> Enable surgeon spawnpoint

Resources/ConfigPresets/Corvax/common.toml
Система настроения временно отключена до переработки.
:cl:
- remove: Отключена система настроений.
=> Отключение системы настроений

Resources/Maps/corvax_awesome.yml, Resources/Maps/corvax_maus.yml, Resources/Maps/corvax_outpost.yml, Resources/Maps/corvax_paper.yml, Resources/Maps/corvax_tushkan.yml
Все турели ЦИИ заменены на Управляемые.
Количество турелей на всех картах от двух до трёх.
=> [Maps] Replace turrets

Resources/Prototypes/_CorvaxNext/Entities/Fun/snowball.yml
- Снежки разбиваются при колизиях на большой скорости
- Снежки можно измельчить в гриндере
Так должно работать
:cl:
- tweak: Снежки теперь можно измельчить
- fix: Снежки также разбиваются при столкновениях на высокой скорости (раньше только при падении на землю)
=> Фикс снежков

Content.IntegrationTests/Tests/PostMapInitTest.cs, Resources/Prototypes/Corvax/Maps/Pools/default.yml, Resources/Prototypes/Corvax/Maps/origin.yml, Resources/Prototypes/Entities/Stations/base.yml, Resources/Prototypes/Maps/amber.yml, Resources/Prototypes/Maps/box.yml, Resources/Prototypes/Maps/cog.yml, Resources/Prototypes/Maps/fland.yml, Resources/Prototypes/Maps/marathon.yml, Resources/Prototypes/Maps/meta.yml, Resources/Prototypes/Maps/omega.yml, Resources/Prototypes/Maps/packed.yml, Resources/Prototypes/Maps/saltern.yml
=> [Maps] Map pool change (#2887)

Content.Shared/_CorvaxNext/TurretControl/Components/TurretControllableComponent.cs, Content.Shared/_CorvaxNext/TurretControl/Components/TurretControllerComponent.cs, Content.Shared/_CorvaxNext/TurretControl/TurretControlComponent.cs, Content.Shared/_CorvaxNext/TurretControl/TurretControlSystem.cs, Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml, Resources/Prototypes/Entities/Mobs/Player/silicon.yml, Resources/Prototypes/_CorvaxNext/Entities/Objects/Weapons/Guns/turrets.yml
Теперь агосты могут видеть и переключать режими управляемых турелей.
Удобство для админов.
:cl:
- tweak: Теперь агосты могут настраивать управляемые турели.
=> Админы и турели

Content.Server/_CorvaxNext/AutoCryoSleep/AutoCryoSleepComponent.cs, Content.Server/_CorvaxNext/AutoCryoSleep/AutoCryoSleepSystem.cs, Content.Server/_CorvaxNext/AutoCryoSleep/AutoCryoSleepableComponent.cs, Content.Shared/_CorvaxNext/NextVars.cs
Добавлена система которая позволяет отправлять членов экипажа в крио капсулы, если они долго находятся в афк.
Заказ KMIN.
=> Cryosleep portals

Content.Shared/_CorvaxNext/TurretControl/Components/TurretControllerComponent.cs, Content.Shared/_CorvaxNext/TurretControl/TurretControlSystem.cs, Resources/Prototypes/Entities/Mobs/Player/silicon.yml
ИИ в интелкарте больше не может управлять турелями.
Багфикс.
:cl:
- fix: ИИ в интелкарте больше не может управлять турелями.
=> Фикс интелкарты и турелей

Resources/Locale/ru-RU/_corvaxnext/abilitties/listen-up.ftl
=> [FIX] Resomi locale

Resources/Maps/Next/next_paper.yml
=> [Maps] Fix Paper

Resources/Prototypes/Corvax/Maps/Next/box.yml
=> [MAPS] Box Update

Resources/Prototypes/Corvax/Maps/Pools/next.yml
Пока Кьют и Перл не отточены, отдельные версии для Некста создаваться не будут.
=> [Maps] Next pool tweaks

Resources/Maps/Next/next_bagel.yml, Resources/Prototypes/Corvax/Maps/Next/bagel.yml
=> [Maps] Bagel roles

Resources/Maps/Next/next_packed.yml
=> [Maps] Packed update #2

Resources/Maps/Next/next_paper.yml
Убран высраный из жопы телепорт киборга.
=> [MAPS] Paperhotfix

Content.Server/_CorvaxNext/Footprints/FootprintSystem.cs
Следы теперь работают по PVS.
Теперь при чистке следов, они будут заменяться на лужу.
:cl:
- tweak: Чистка следов будет заменять их на лужу.
=> Фиксы следов

Content.Server/Objectives/Commands/ListObjectivesCommand.cs
Теперь `lsobjectives` доступно всем админам.
=> Admin list objectives

.github/workflows/publish.yml
=> Silly change to push a new commit SHA

Resources/Prototypes/Corvax/Maps/Corvax/cute.yml, Resources/Prototypes/Corvax/Maps/Next/bagel.yml, Resources/Prototypes/Corvax/Maps/Pools/next.yml
sync [#3037](https://github.com/space-syndicate/space-station-14/pull/3037)
=> sync Map pool tweaks & semi-pops #3037

Resources/Textures/Clothing/OuterClothing/Vests/hazard.rsi/meta.json
bruh validator
исправил ошибку rsi validator'а со спрайтом резоми
=> hotfix resomi sptrite

Resources/Prototypes/Body/Organs/Animal/animal.yml, Resources/Prototypes/Body/Organs/human.yml, Resources/Prototypes/Entities/Clothing/Masks/masks.yml
=> HotFixRitualTag

Resources/Prototypes/Recipes/Lathes/Packs/service.yml
Вернул диктофон и кассеты в автолат
Диктофон нужен
=> Возвращение диктофона и кассет в автолат

Resources/Prototypes/Body/Organs/Animal/animal.yml, Resources/Prototypes/Body/Organs/Animal/slimes.yml, Resources/Prototypes/Body/Organs/human.yml, Resources/Prototypes/Body/Organs/moth.yml, Resources/Prototypes/Body/Organs/rat.yml, Resources/Prototypes/Body/Organs/slime.yml, Resources/Prototypes/Body/Organs/vox.yml
=> FixHereticRitual2

Resources/Prototypes/GameRules/events.yml
Исправил генерацию имени для Космического Ниндзя.
bug fix
Добавил сегменты имени в прототип геймрула.
=> Исправление имени Ниндзя

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/HMGs/hmgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/LMGs/lmgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Launchers/launchers.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Rifles/rifles.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/SMGs/smgs.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Shotguns/shotguns.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml
=> Shooting skill fix

Resources/Prototypes/Corvax/Maps/Corvax/astra.yml, Resources/Prototypes/Corvax/Maps/Corvax/frame.yml, Resources/Prototypes/Corvax/Maps/Corvax/gelta.yml, Resources/Prototypes/Corvax/Maps/Corvax/ishimura.yml, Resources/Prototypes/Corvax/Maps/Pools/next.yml, Resources/Prototypes/Maps/Relic.yml
=> April map pool

Resources/Prototypes/Corvax/Maps/Corvax/frame.yml
=> april fools map pool fix

Resources/Prototypes/Entities/Objects/Devices/pda.yml, Resources/Prototypes/Entities/Structures/Machines/lathe.yml, Resources/Prototypes/Recipes/Lathes/Packs/medical.yml, Resources/Prototypes/Recipes/Lathes/Packs/service.yml, Resources/Prototypes/Recipes/Lathes/misc.yml, Resources/Prototypes/_CorvaxNext/Recipes/Lathes/Misc.yml, Resources/Prototypes/_CorvaxNext/Recipes/Lathes/Packs/botany.yml, Resources/Prototypes/_CorvaxNext/Recipes/Lathes/Packs/service.yml, Resources/Prototypes/game_presets.yml
Вернул в рецепты медфаба костяной гель. В кпк Капитана, Квартирмейстера и Репортёра добавил картридж НаноТаск. Небольшие перестановки в рецептах.
Фикс + немного отсебятины.
Перенёс рецепты диктофона и кассет в папку Некста т.к. предметы присутствуют только тут.
Выделил под диктофон и кассеты отдельный пак NextServiceStatic, чтобы в дальнейшем туда добавлять появляющеся предметы (так удобнее будет, я вас уверяю).
Перенёс пак с анализатором растений в файл service.yml, опять же для удобства.
=> Немного исправлений

Resources/Prototypes/Corvax/Maps/Corvax/frame.yml
Reverts space-syndicate/space-station-14-next#327
=> Revert "april fools map pool fix"

Content.Server/_CorvaxNext/BattleRoyale/DynamicRange/DynamicRangeSystem.cs, Content.Shared/_CorvaxNext/BattleRoyale/DynamicRange/DynamicRangeComponent.cs, Resources/Audio/_CorvaxNext/Music/attributions.yml, Resources/Maps/_CorvaxNext/Nonstations/battleroyale.yml, Resources/Prototypes/_CorvaxNext/Entities/Markers/Spawners/Random/BattleRoyale/weapons.yml, Resources/Prototypes/_CorvaxNext/SoundCollections/battleroyale.yml
Все еще не надо писать об этом в ченджлог.
Фиксы Королевской Битвы по итогу тестов.
Твердые границы зоны безопасности удалены.
Несколько видов стволов удалено из спавнов.
Оружие теперь спавнится реже.
Добавлен музыкальный трек для режима.
Добавлено больше медикаментов.
По итогу тестов с аудиторией.
=> Фиксы Королевской Битвы

Resources/Maps/Next/next_maus.yml
=> [Maps] Maus salvage fix

Resources/Maps/Next/next_cute.yml
=> [Maps] Cute fix

Resources/Maps/Next/next_pearl.yml
=> [Maps] Pearl fix

.github/workflows/publish.yml
=> Ingest new version for CDN

Resources/Prototypes/Roles/Jobs/CentComm/deathsquad.yml
Добавил скилл - type: CanChokeGrab ОБР, РХБЗЗ, Эскадрону Смерти
добавил - type: CanChokeGrab
просто добавил - type: CanChokeGrab 
=> fix-grab-system

Resources/Locale/ru-RU/station-events/events/ion-storm.ftl, Resources/Prototypes/GameRules/events.yml
Добавил звук шторма к его ивенту.
Потому что так более рпшно и будет логическая причина "шмонать" борго на законы. 
:cl:
- tweak: Привязан звук ионного шторма к его ивенту.
=> Привязал звук ионного шторма к его ивенту.yml

Resources/Prototypes/Corvax/Maps/Next/delta.yml
Упростил подключение соляр, убрал ненужные спауны, микро изменения инженерного отдела. Небольшие изменения на карте. Изменено кол-во ролей в прототипе и минимальное кол-во игроков.
=> Микро фиксы на дальте и в прототипе

Content.IntegrationTests/Tests/PostMapInitTest.cs, Resources/Prototypes/Corvax/Maps/Next/chloris.yml, Resources/Prototypes/Corvax/Maps/Pools/next.yml
=> [Maps] NextChloris

Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Добавил навыки всем боргам.
Их у них не было увы.
Добавил навыки всем боргам на уровне базы боргов, т.к. на уровне джобки так не получается сделать.
:cl:
- add: Добавлены навыки боргам.
=> Skills for Cyborgs

Resources/Locale/en-US/_corvaxnext/preferences/loadout-groups.ftl, Resources/Prototypes/_CorvaxNext/Loadouts/loadouts_groups.yml, Resources/Prototypes/_CorvaxNext/Loadouts/role_loadouts.yml
Починил хирурга.
Как я понял, при переносе бма с основы на некст(проще говоря перенос с папки некст в папку основы), не много так захуярили файлы хирурга. И вот я их восстановил для работоспособности
Вернул loadouts_groups.yml и role_loadouts.yml. Добавил en-US локаль loadout для хирурга.
:cl:
- fix: Исправлены лоадауты и одежда хирурга.
=> FixSurgeon

Resources/Maps/Next/next_paper.yml
На бокс добавлено помещение в рнд "токсикология".
На боксе чутка изменена комната тега.
Изменены турели в ядрах ИИ.
=> [MAPS] Папир И бокс ИИ турели

Resources/Maps/Next/next_amber.yml, Resources/Maps/Next/next_awesome.yml, Resources/Maps/Next/next_bagel.yml, Resources/Maps/Next/next_marathon.yml, Resources/Maps/Next/next_maus.yml, Resources/Maps/Next/next_omega.yml, Resources/Maps/Next/next_outpost.yml, Resources/Maps/Next/next_packed.yml, Resources/Maps/Next/next_paper.yml, Resources/Maps/Next/next_pearl.yml, Resources/Maps/Next/next_silly.yml, Resources/Maps/Next/next_tushkan.yml, Resources/Prototypes/Corvax/Maps/Next/amber.yml, Resources/Prototypes/Corvax/Maps/Next/astra.yml, Resources/Prototypes/Corvax/Maps/Next/avrite.yml, Resources/Prototypes/Corvax/Maps/Next/awesome.yml, Resources/Prototypes/Corvax/Maps/Next/bagel.yml, Resources/Prototypes/Corvax/Maps/Next/box.yml, Resources/Prototypes/Corvax/Maps/Next/chloris.yml, Resources/Prototypes/Corvax/Maps/Next/delta.yml, Resources/Prototypes/Corvax/Maps/Next/marathon.yml, Resources/Prototypes/Corvax/Maps/Next/maus.yml, Resources/Prototypes/Corvax/Maps/Next/omega.yml, Resources/Prototypes/Corvax/Maps/Next/outpost.yml, Resources/Prototypes/Corvax/Maps/Next/packed.yml, Resources/Prototypes/Corvax/Maps/Next/paper.yml, Resources/Prototypes/Corvax/Maps/Next/pearl.yml, Resources/Prototypes/Corvax/Maps/Next/pilgrim.yml, Resources/Prototypes/Corvax/Maps/Next/silly.yml, Resources/Prototypes/Corvax/Maps/Next/tushkan.yml
На все карты добавлен Помощник Смотрителя.
Спавнеры торгоматов еды заменены на [нужные](https://github.com/space-syndicate/space-station-14-next/pull/396) по популяции.
=> Warden Helper and Snack vending added to all maps

Resources/Prototypes/Roles/Jobs/Security/warden.yml
Гарнитура смотрителя заменена на гарнитуру ГСБ чтобы была командная волна.
Помощнику Вардена специально не добавил.
https://discord.com/channels/919301044784226385/1376476023616442419
=> Change Warden headset

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Доступ к консоли распределения бюджета изменен с ГП на КМ.
В качестве эксперимента по результатам [опроса](https://discordapp.com/channels/919301044784226385/1084254414388347001/1380073482343415808) (я бы все-равно сделал демократии не существует).
Не факт что изменение останется.
=> Funding console access change

Resources/Maps/Next/next_marathon.yml
Добавил сило, голопады, то, чего не было.
=> [Maps] MarathonUpdate 2

Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Стрельба из
- Тренировочная лазерная винтовка
- Лазерная винтовка
- Старомодный лазерный пистолет
- Рентгеновская лазерная винтовка
больше не зависит от навыка владения оружием
=> Lasers gun requires skill tweak

Resources/Prototypes/Corvax/Maps/Next/void.yml
Убрал overflowJobs, которое уже не используется
=> [Maps] Void hotfix

Resources/Prototypes/Corvax/Maps/Next/pilgrim.yml, Resources/Prototypes/Corvax/Maps/Pools/next.yml
Минимальный онлайн Пилигрима изменен с 40 до 55.
=> [Maps] Pilgrim tweak

Resources/Prototypes/Corvax/Maps/Next/bagel.yml, Resources/Prototypes/Corvax/Maps/Next/void.yml, Resources/Prototypes/Corvax/Maps/Pools/next.yml
Временно вырезана категория семи-хайпоп, а также скучные правки в прототипах
=> [Maps] Boring proto tweaks

Resources/Prototypes/GameRules/events.yml, Resources/Prototypes/_CorvaxNext/GameRules/events.yml
https://discord.com/channels/919301044784226385/1389631837118398496
:cl:
- tweak: Изменен шанс появления крупных антагонистов.
=> Change weight midround

Resources/Prototypes/Corvax/Maps/Next/delta.yml, Resources/Prototypes/Corvax/Maps/Next/maus.yml, Resources/Prototypes/Corvax/Maps/Pools/next.yml
Семи-попы ВСЁ! Игра слишком хуево ролит карты, если их онлайн отличается.
Дельта снова начинается с 55 онлайна.
Маус выпадает до 25.
=> Maps online

Resources/Prototypes/_CorvaxNext/Entities/Objects/Devices/pda.yml
Как появился хирург, все думали что ему просто не досталось спрайта, но правда была проще... Ko4erga зажал ему 5 строчек, спустя долгое время, пда хирурга получил свои 5 строчек спрайта.
Не ну а хули?
https://discord.com/channels/919301044784226385/1399083319102148739
Из игры прислать не могу ибо раунд даже не стартается, но вот как в файлах он:
:cl:
- fix: Исправлен спрайт КПК хирурга!
=> fix surgeonPDA

Resources/Prototypes/Entities/Mobs/NPCs/regalrat.yml
код по предложке - добавлено ночное виденье для короля крыс
https://discord.com/channels/919301044784226385/1388228449872904283
=> nightwision для короля крсы

Resources/Prototypes/Entities/Mobs/NPCs/human.yml
Добавил имена и слоты для неизвестных трупов
Для хирургий, но КПК с доступами появились.
Изменил только 2 строчки в прототипах. Все изменения добавил # Corvax
:tools: У неизвестных трупов появилась имена и все слоты на теле.
=> Corpse has all slots now. And now have name. 

Resources/Prototypes/Entities/Clothing/OuterClothing/suits.yml
Добавил AllowSuitStorageClothingGasTanks в parent для ClothingOuterSuitBomb, чтобы можно было на спину закинуть баллон с кислородом
https://discord.com/channels/919301044784226385/1398200150978990101
Ну добавил компонентик в родаки саперному костюму
[video.webm](https://github.com/user-attachments/assets/7c4115c6-ebb9-4872-a380-3ec6216aaf32)
:cl:
- tweak: Сапёрный костюм теперь дружит с баллонами
=> Add AllowSuitStorageClothingGasTanks to ClothingOuterSuitBomb

Resources/Maps/Next/next_pearl.yml, Resources/Maps/Next/next_silly.yml
https://github.com/space-syndicate/space-station-14/pull/3365/files
=> FixParallax
